name: Run Pytest

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - run: pipx install poetry==2.1.1

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        cache: poetry

    - name: Install test
      run: poetry install

    - name: Test
      run: poetry run pytest -v
